#ifndef DEF_H
#define DEF_H

#include <stdio.h>

// TODO: macro debug message

// return value
#define SUCCESS (0)
#define FAILED  (-1)

enum Expression
{
    UINT,
    STR,
    V4ADDR,
    V6ADDR,
    OTHERS,
    UNDEFINE
};

typedef struct
{
    enum Expression exp;
    int value;
    char* fieldType;
}value_string3;

typedef struct
{
    int value;
    char* fieldType;
}value_string2;

/* If you want sort of safely to send enterprise specific element IDs
   using v9 you need to stake a claim in the wilds with the high bit
   set.  Still no naming authority, but at least it will never collide
   with valid IPFIX */
#define NTOP_BASE 57472u                /* nprobe >= 5.5.6 */

//TODO: use function query, not fixed

static const value_string3 v9_template_types[] = {
    { UNDEFINE,   0, "NULL" },
    { UINT,       1, "BYTES" },
    { UINT,       2, "PKTS" },
    { UINT,       3, "FLOWS" },
    { UINT,       4, "PROTOCOL" },
    { UNDEFINE,   5, "IP_TOS" },
    { UNDEFINE,   6, "TCP_FLAGS" },
    { UINT,       7, "L4_SRC_PORT" },
    { V4ADDR,     8, "IP_SRC_ADDR" },
    { UINT,       9, "SRC_MASK" },
    { UNDEFINE,  10, "INPUT_SNMP" },
    { UINT,      11, "L4_DST_PORT" },
    { V4ADDR,    12, "IP_DST_ADDR" },
    { UNDEFINE,  13, "DST_MASK" },
    { UNDEFINE,  14, "OUTPUT_SNMP" },
    { UNDEFINE,  15, "IP_NEXT_HOP" },
    { UNDEFINE,  16, "SRC_AS" },
    { UNDEFINE,  17, "DST_AS" },
    { UNDEFINE,  18, "BGP_NEXT_HOP" },
    { UNDEFINE,  19, "MUL_DPKTS" },
    { UNDEFINE,  20, "MUL_DOCTETS" },
    { UNDEFINE,  21, "LAST_SWITCHED" },
    { UNDEFINE,  22, "FIRST_SWITCHED" },
    { UNDEFINE,  23, "OUT_BYTES" },
    { UNDEFINE,  24, "OUT_PKTS" },
    { UNDEFINE,  25, "IP LENGTH MINIMUM" },
    { UNDEFINE,  26, "IP LENGTH MAXIMUM" },
    { UNDEFINE,  27, "IPV6_SRC_ADDR" },
    { UNDEFINE,  28, "IPV6_DST_ADDR" },
    { UNDEFINE,  29, "IPV6_SRC_MASK" },
    { UNDEFINE,  30, "IPV6_DST_MASK" },
    { UNDEFINE,  31, "FLOW_LABEL" },
    { UNDEFINE,  32, "ICMP_TYPE" },
    { UNDEFINE,  33, "IGMP_TYPE" },
    { UNDEFINE,  34, "SAMPLING_INTERVAL" },
    { UNDEFINE,  35, "SAMPLING_ALGORITHM" },
    { UNDEFINE,  36, "FLOW_ACTIVE_TIMEOUT" },
    { UNDEFINE,  37, "FLOW_INACTIVE_TIMEOUT" },
    { UNDEFINE,  38, "ENGINE_TYPE" },
    { UNDEFINE,  39, "ENGINE_ID" },
    { UNDEFINE,  40, "TOTAL_BYTES_EXP" },
    { UNDEFINE,  41, "TOTAL_PKTS_EXP" },
    { UNDEFINE,  42, "TOTAL_FLOWS_EXP" },
    { UNDEFINE,  44, "IP_SRC_PREFIX" },
    { UNDEFINE,  45, "IP_DST_PREFIX" },
    { UNDEFINE,  46, "MPLS_TOP_LABEL_TYPE" },
    { UNDEFINE,  47, "MPLS_TOP_LABEL_ADDR" },
    { UNDEFINE,  48, "FLOW_SAMPLER_ID" },
    { UNDEFINE,  49, "FLOW_SAMPLER_MODE" },
    { UNDEFINE,  50, "FLOW_SAMPLER_RANDOM_INTERVAL" },
    { UNDEFINE,  51, "FLOW_CLASS" },
    { UNDEFINE,  52, "IP TTL MINIMUM" },
    { UNDEFINE,  53, "IP TTL MAXIMUM" },
    { UNDEFINE,  54, "IPv4 ID" },
    { UNDEFINE,  55, "DST_TOS" },
    { UNDEFINE,  56, "SRC_MAC" },
    { UNDEFINE,  57, "DST_MAC" },
    { UNDEFINE,  58, "SRC_VLAN" },
    { UNDEFINE,  59, "DST_VLAN" },
    { UNDEFINE,  60, "IP_PROTOCOL_VERSION" },
    { UNDEFINE,  61, "DIRECTION" },
    { UNDEFINE,  62, "IPV6_NEXT_HOP" },
    { UNDEFINE,  63, "BGP_IPV6_NEXT_HOP" },
    { UNDEFINE,  64, "IPV6_OPTION_HEADERS" },
    { UNDEFINE,  70, "MPLS_LABEL_1" },
    { UNDEFINE,  71, "MPLS_LABEL_2" },
    { UNDEFINE,  72, "MPLS_LABEL_3" },
    { UNDEFINE,  73, "MPLS_LABEL_4" },
    { UNDEFINE,  74, "MPLS_LABEL_5" },
    { UNDEFINE,  75, "MPLS_LABEL_6" },
    { UNDEFINE,  76, "MPLS_LABEL_7" },
    { UNDEFINE,  77, "MPLS_LABEL_8" },
    { UNDEFINE,  78, "MPLS_LABEL_9" },
    { UNDEFINE,  79, "MPLS_LABEL_10" },
    { UNDEFINE,  80, "DESTINATION_MAC" },
    { UNDEFINE,  81, "SOURCE_MAC" },
    { UNDEFINE,  82, "IF_NAME" },
    { UNDEFINE,  83, "IF_DESC" },
    { UNDEFINE,  84, "SAMPLER_NAME" },
    { UNDEFINE,  85, "BYTES_TOTAL" },
    { UNDEFINE,  86, "PACKETS_TOTAL" },
    { UNDEFINE,  88, "FRAGMENT_OFFSET" },
    { UNDEFINE,  89, "FORWARDING_STATUS" },
    { UNDEFINE,  90, "VPN_ROUTE_DISTINGUISHER" },
    { UNDEFINE,  91, "mplsTopLabelPrefixLength" },
    { UNDEFINE,  92, "SRC_TRAFFIC_INDEX" },
    { UNDEFINE,  93, "DST_TRAFFIC_INDEX" },
    { UNDEFINE,  94, "APPLICATION_DESC" },
    { UNDEFINE,  95, "APPLICATION_ID" },
    { UNDEFINE,  96, "APPLICATION_NAME" },
    { UNDEFINE,  98, "postIpDiffServCodePoint" },
    { UNDEFINE,  99, "multicastReplicationFactor" },
    { UNDEFINE, 128, "DST_AS_PEER" },
    { UNDEFINE, 129, "SRC_AS_PEER" },
    { UNDEFINE, 130, "exporterIPv4Address" },
    { UNDEFINE, 131, "exporterIPv6Address" },
    { UNDEFINE, 132, "DROPPED_BYTES" },
    { UNDEFINE, 133, "DROPPED_PACKETS" },
    { UNDEFINE, 134, "DROPPED_BYTES_TOTAL" },
    { UNDEFINE, 135, "DROPPED_PACKETS_TOTAL" },
    { UNDEFINE, 136, "flowEndReason" },
    { UNDEFINE, 137, "commonPropertiesId" },
    { UNDEFINE, 138, "observationPointId" },
    { UNDEFINE, 139, "icmpTypeCodeIPv6" },
    { UNDEFINE, 140, "MPLS_TOP_LABEL_IPv6_ADDRESS" },
    { UNDEFINE, 141, "lineCardId" },
    { UNDEFINE, 142, "portId" },
    { UNDEFINE, 143, "meteringProcessId" },
    { UNDEFINE, 144, "FLOW_EXPORTER" },
    { UNDEFINE, 145, "templateId" },
    { UNDEFINE, 146, "wlanChannelId" },
    { UNDEFINE, 147, "wlanSSID" },
    { UNDEFINE, 148, "flowId" },
    { UNDEFINE, 149, "observationDomainId" },
    { UNDEFINE, 150, "flowStartSeconds" },
    { UNDEFINE, 151, "flowEndSeconds" },
    { UNDEFINE, 152, "flowStartMilliseconds" },
    { UNDEFINE, 153, "flowEndMilliseconds" },
    { UNDEFINE, 154, "flowStartMicroseconds" },
    { UNDEFINE, 155, "flowEndMicroseconds" },
    { UNDEFINE, 156, "flowStartNanoseconds" },
    { UNDEFINE, 157, "flowEndNanoseconds" },
    { UNDEFINE, 158, "flowStartDeltaMicroseconds" },
    { UNDEFINE, 159, "flowEndDeltaMicroseconds" },
    { UNDEFINE, 160, "systemInitTimeMilliseconds" },
    { UNDEFINE, 161, "flowDurationMilliseconds" },
    { UNDEFINE, 162, "flowDurationMicroseconds" },
    { UNDEFINE, 163, "observedFlowTotalCount" },
    { UNDEFINE, 164, "ignoredPacketTotalCount" },
    { UNDEFINE, 165, "ignoredOctetTotalCount" },
    { UNDEFINE, 166, "notSentFlowTotalCount" },
    { UNDEFINE, 167, "notSentPacketTotalCount" },
    { UNDEFINE, 168, "notSentOctetTotalCount" },
    { UNDEFINE, 169, "destinationIPv6Prefix" },
    { UNDEFINE, 170, "sourceIPv6Prefix" },
    { UNDEFINE, 171, "postOctetTotalCount" },
    { UNDEFINE, 172, "postPacketTotalCount" },
    { UNDEFINE, 173, "flowKeyIndicator" },
    { UNDEFINE, 174, "postMCastPacketTotalCount" },
    { UNDEFINE, 175, "postMCastOctetTotalCount" },
    { UNDEFINE, 176, "ICMP_IPv4_TYPE" },
    { UNDEFINE, 177, "ICMP_IPv4_CODE" },
    { UNDEFINE, 178, "ICMP_IPv6_TYPE" },
    { UNDEFINE, 179, "ICMP_IPv6_CODE" },
    { UNDEFINE, 180, "UDP_SRC_PORT" },
    { UNDEFINE, 181, "UDP_DST_PORT" },
    { UNDEFINE, 182, "TCP_SRC_PORT" },
    { UNDEFINE, 183, "TCP_DST_PORT" },
    { UNDEFINE, 184, "TCP_SEQ_NUM" },
    { UNDEFINE, 185, "TCP_ACK_NUM" },
    { UNDEFINE, 186, "TCP_WINDOW_SIZE" },
    { UNDEFINE, 187, "TCP_URGENT_PTR" },
    { UNDEFINE, 188, "TCP_HEADER_LEN" },
    { UNDEFINE, 189, "IP_HEADER_LEN" },
    { UNDEFINE, 190, "IP_TOTAL_LEN" },
    { UNDEFINE, 191, "payloadLengthIPv6" },
    { UNDEFINE, 192, "IP_TTL" },
    { UNDEFINE, 193, "nextHeaderIPv6" },
    { UNDEFINE, 194, "IP_TOS" },
    { UNDEFINE, 195, "IP_DSCP" },
    { UNDEFINE, 196, "IP_PRECEDENCE" },
    { UNDEFINE, 197, "IP_FRAGMENT_FLAGS" },
    { UNDEFINE, 198, "BYTES_SQUARED" },
    { UNDEFINE, 199, "BYTES_SQUARED_PERMANENT" },
    { UNDEFINE, 200, "MPLS_TOP_LABEL_TTL" },
    { UNDEFINE, 201, "MPLS_LABEL_STACK_OCTETS" },
    { UNDEFINE, 202, "MPLS_LABEL_STACK_DEPTH" },
    { UNDEFINE, 203, "MPLS_TOP_LABEL_EXP" },
    { UNDEFINE, 204, "IP_PAYLOAD_LENGTH" },
    { UNDEFINE, 205, "UDP_LENGTH" },
    { UNDEFINE, 206, "IS_MULTICAST" },
    { UNDEFINE, 207, "IP_HEADER_WORDS" },
    { UNDEFINE, 208, "IP_OPTION_MAP" },
    { UNDEFINE, 209, "TCP_OPTION_MAP" },
    { UNDEFINE, 210, "paddingOctets" },
    { UNDEFINE, 211, "collectorIPv4Address" },
    { UNDEFINE, 212, "collectorIPv6Address" },
    { UNDEFINE, 213, "collectorInterface" },
    { UNDEFINE, 214, "collectorProtocolVersion" },
    { UNDEFINE, 215, "collectorTransportProtocol" },
    { UNDEFINE, 216, "collectorTransportPort" },
    { UNDEFINE, 217, "exporterTransportPort" },
    { UNDEFINE, 218, "tcpSynTotalCount" },
    { UNDEFINE, 219, "tcpFinTotalCount" },
    { UNDEFINE, 220, "tcpRstTotalCount" },
    { UNDEFINE, 221, "tcpPshTotalCount" },
    { UNDEFINE, 222, "tcpAckTotalCount" },
    { UNDEFINE, 223, "tcpUrgTotalCount" },
    { UNDEFINE, 224, "ipTotalLength" },
    { UNDEFINE, 225, "postNATSourceIPv4Address" },
    { UNDEFINE, 226, "postNATDestinationIPv4Address" },
    { UNDEFINE, 227, "postNAPTSourceTransportPort" },
    { UNDEFINE, 228, "postNAPTDestinationTransportPort" },
    { UNDEFINE, 229, "natOriginatingAddressRealm" },
    { UNDEFINE, 230, "natEvent" },
    { UNDEFINE, 231, "initiatorOctets" },
    { UNDEFINE, 232, "responderOctets" },
    { UNDEFINE, 233, "firewallEvent" },
    { UNDEFINE, 234, "ingressVRFID" },
    { UNDEFINE, 235, "egressVRFID" },
    { UNDEFINE, 236, "VRFname" },
    { UNDEFINE, 237, "postMplsTopLabelExp" },
    { UNDEFINE, 238, "tcpWindowScale" },
    { UNDEFINE, 239, "biflowDirection" },
    { UNDEFINE, 240, "ethernetHeaderLength" },
    { UNDEFINE, 241, "ethernetPayloadLength" },
    { UNDEFINE, 242, "ethernetTotalLength" },
    { UNDEFINE, 243, "dot1qVlanId" },
    { UNDEFINE, 244, "dot1qPriority" },
    { UNDEFINE, 245, "dot1qCustomerVlanId" },
    { UNDEFINE, 246, "dot1qCustomerPriority" },
    { UNDEFINE, 247, "metroEvcId" },
    { UNDEFINE, 248, "metroEvcType" },
    { UNDEFINE, 249, "pseudoWireId" },
    { UNDEFINE, 250, "pseudoWireType" },
    { UNDEFINE, 251, "pseudoWireControlWord" },
    { UNDEFINE, 252, "ingressPhysicalInterface" },
    { UNDEFINE, 253, "egressPhysicalInterface" },
    { UNDEFINE, 254, "postDot1qVlanId" },
    { UNDEFINE, 255, "postDot1qCustomerVlanId" },
    { UNDEFINE, 256, "ethernetType" },
    { UNDEFINE, 257, "postIpPrecedence" },
    { UNDEFINE, 258, "collectionTimeMilliseconds" },
    { UNDEFINE, 259, "exportSctpStreamId" },
    { UNDEFINE, 260, "maxExportSeconds" },
    { UNDEFINE, 261, "maxFlowEndSeconds" },
    { UNDEFINE, 262, "messageMD5Checksum" },
    { UNDEFINE, 263, "messageScope" },
    { UNDEFINE, 264, "minExportSeconds" },
    { UNDEFINE, 265, "minFlowStartSeconds" },
    { UNDEFINE, 266, "opaqueOctets" },
    { UNDEFINE, 267, "sessionScope" },
    { UNDEFINE, 268, "maxFlowEndMicroseconds" },
    { UNDEFINE, 269, "maxFlowEndMilliseconds" },
    { UNDEFINE, 270, "maxFlowEndNanoseconds" },
    { UNDEFINE, 271, "minFlowStartMicroseconds" },
    { UNDEFINE, 272, "minFlowStartMilliseconds" },
    { UNDEFINE, 273, "minFlowStartNanoseconds" },
    { UNDEFINE, 274, "collectorCertificate" },
    { UNDEFINE, 275, "exporterCertificate" },
    { UNDEFINE, 301, "selectionSequenceId" },
    { UNDEFINE, 302, "selectorId" },
    { UNDEFINE, 303, "informationElementId" },
    { UNDEFINE, 304, "selectorAlgorithm" },
    { UNDEFINE, 305, "samplingPacketInterval" },
    { UNDEFINE, 306, "samplingPacketSpace" },
    { UNDEFINE, 307, "samplingTimeInterval" },
    { UNDEFINE, 308, "samplingTimeSpace" },
    { UNDEFINE, 309, "samplingSize" },
    { UNDEFINE, 310, "samplingPopulation" },
    { UNDEFINE, 311, "samplingProbability" },
    { UNDEFINE, 313, "IP_SECTION HEADER" },
    { UNDEFINE, 314, "IP_SECTION PAYLOAD" },
    { UNDEFINE, 316, "mplsLabelStackSection" },
    { UNDEFINE, 317, "mplsPayloadPacketSection" },
    { UNDEFINE, 318, "selectorIdTotalPktsObserved" },
    { UNDEFINE, 319, "selectorIdTotalPktsSelected" },
    { UNDEFINE, 320, "absoluteError" },
    { UNDEFINE, 321, "relativeError" },
    { UNDEFINE, 322, "observationTimeSeconds" },
    { UNDEFINE, 323, "observationTimeMilliseconds" },
    { UNDEFINE, 324, "observationTimeMicroseconds" },
    { UNDEFINE, 325, "observationTimeNanoseconds" },
    { UNDEFINE, 326, "digestHashValue" },
    { UNDEFINE, 327, "hashIPPayloadOffset" },
    { UNDEFINE, 328, "hashIPPayloadSize" },
    { UNDEFINE, 329, "hashOutputRangeMin" },
    { UNDEFINE, 330, "hashOutputRangeMax" },
    { UNDEFINE, 331, "hashSelectedRangeMin" },
    { UNDEFINE, 332, "hashSelectedRangeMax" },
    { UNDEFINE, 333, "hashDigestOutput" },
    { UNDEFINE, 334, "hashInitialiserValue" },
    { UNDEFINE, 335, "selectorName" },
    { UNDEFINE, 336, "upperCILimit" },
    { UNDEFINE, 337, "lowerCILimit" },
    { UNDEFINE, 338, "confidenceLevel" },
    { UNDEFINE, 339, "informationElementDataType" },
    { UNDEFINE, 340, "informationElementDescription" },
    { UNDEFINE, 341, "informationElementName" },
    { UNDEFINE, 342, "informationElementRangeBegin" },
    { UNDEFINE, 343, "informationElementRangeEnd" },
    { UNDEFINE, 344, "informationElementSemantics" },
    { UNDEFINE, 345, "informationElementUnits" },
    { UNDEFINE, 346, "privateEnterpriseNumber" },
    /* Ericsson NAT Logging */
    { UNDEFINE, 24628, "NAT_LOG_FIELD_IDX_CONTEXT_ID" },
    { UNDEFINE, 24629, "NAT_LOG_FIELD_IDX_CONTEXT_NAME" },
    { UNDEFINE, 24630, "NAT_LOG_FIELD_IDX_ASSIGN_TS_SEC" },
    { UNDEFINE, 24631, "NAT_LOG_FIELD_IDX_UNASSIGN_TS_SEC" },
    { UNDEFINE, 24632, "NAT_LOG_FIELD_IDX_IPV4_INT_ADDR" },
    { UNDEFINE, 24633, "NAT_LOG_FIELD_IDX_IPV4_EXT_ADDR" },
    { UNDEFINE, 24634, "NAT_LOG_FIELD_IDX_EXT_PORT_FIRST" },
    { UNDEFINE, 24635, "NAT_LOG_FIELD_IDX_EXT_PORT_LAST" },
    /* Cisco ASA5500 Series NetFlow */
    { UNDEFINE, 33000, "INGRESS_ACL_ID" },
    { UNDEFINE, 33001, "EGRESS_ACL_ID" },
    { UNDEFINE, 33002, "FW_EXT_EVENT" },
    /* Cisco TrustSec */
    { UNDEFINE, 34000, "SGT_SOURCE_TAG" },
    { UNDEFINE, 34001, "SGT_DESTINATION_TAG" },
    { UNDEFINE, 34002, "SGT_SOURCE_NAME" },
    { UNDEFINE, 34003, "SGT_DESTINATION_NAME" },
    /* Boundary bprobe */
    { UNDEFINE, 33610, "METER_VERSION"},
    { UNDEFINE, 33611, "METER_OS_SYSNAME"},
    { UNDEFINE, 33612, "METER_OS_NODENAME"},
    { UNDEFINE, 33613, "METER_OS_RELEASE"},
    { UNDEFINE, 33614, "METER_OS_VERSION"},
    { UNDEFINE, 33615, "METER_OS_MACHINE"},
    { UNDEFINE, 33623, "EPOCH_SECOND"},
    { UNDEFINE, 33624, "NIC_NAME"},
    { UNDEFINE, 33625, "NIC_ID"},
    { UNDEFINE, 33626, "NIC_MAC"},
    { UNDEFINE, 33627, "NIC_IP"},
    { UNDEFINE, 33628, "COLLISIONS"},
    { UNDEFINE, 33629, "ERRORS"},
    { UNDEFINE, 33630, "NIC_DRIVER_NAME"},
    { UNDEFINE, 33631, "NIC_DRIVER_VERSION"},
    { UNDEFINE, 33632, "NIC_FIRMWARE_VERSION"},
    { UNDEFINE, 33633, "METER_OS_DISTRIBUTION_NAME"},
    { UNDEFINE, 33634, "BOND_INTERFACE_MODE"},
    { UNDEFINE, 33635, "BOND_INTERFACE_PHYSICAL_NIC_COUNT"},
    { UNDEFINE, 33636, "BOND_INTERFACE_ID"},
    /* medianet performance monitor */
    { UNDEFINE, 37000, "PACKETS_DROPPED" },
    { UNDEFINE, 37003, "BYTE_RATE" },
    { UNDEFINE, 37004, "APPLICATION_MEDIA_BYTES" },
    { UNDEFINE, 37006, "APPLICATION_MEDIA_BYTE_RATE" },
    { UNDEFINE, 37007, "APPLICATION_MEDIA_PACKETS" },
    { UNDEFINE, 37009, "APPLICATION_MEDIA_PACKET_RATE" },
    { UNDEFINE, 37011, "APPLICATION_MEDIA_EVENT" },
    { UNDEFINE, 37012, "MONITOR_EVENT" },
    { UNDEFINE, 37013, "TIMESTAMP_INTERVAL" },
    { UNDEFINE, 37014, "TRANSPORT_PACKETS_EXPECTED" },
    { UNDEFINE, 37016, "TRANSPORT_ROUND_TRIP_TIME" },
    { UNDEFINE, 37017, "TRANSPORT_EVENT_PACKET_LOSS" },
    { UNDEFINE, 37019, "TRANSPORT_PACKETS_LOST" },
    { UNDEFINE, 37021, "TRANSPORT_PACKETS_LOST_RATE" },
    { UNDEFINE, 37022, "TRANSPORT_RTP_SSRC" },
    { UNDEFINE, 37023, "TRANSPORT_RTP_JITTER_MEAN" },
    { UNDEFINE, 37024, "TRANSPORT_RTP_JITTER_MIN" },
    { UNDEFINE, 37025, "TRANSPORT_RTP_JITTER_MAX" },
    { UNDEFINE, 37041, "TRANSPORT_RTP_PAYLOAD_TYPE" },
    { UNDEFINE, 37071, "TRANSPORT_BYTES_OUT_OF_ORDER" },
    { UNDEFINE, 37074, "TRANSPORT_PACKETS_OUT_OF_ORDER" },
    { UNDEFINE, 37083, "TRANSPORT_TCP_WINDOWS_SIZE_MIN" },
    { UNDEFINE, 37084, "TRANSPORT_TCP_WINDOWS_SIZE_MAX" },
    { UNDEFINE, 37085, "TRANSPORT_TCP_WINDOWS_SIZE_MEAN" },
    { UNDEFINE, 37086, "TRANSPORT_TCP_MAXIMUM_SEGMENT_SIZE" },
    { UNDEFINE, 40000, "AAA_USERNAME" },
    { UNDEFINE, 40001, "XLATE_SRC_ADDR_IPV4" },
    { UNDEFINE, 40002, "XLATE_DST_ADDR_IPV4" },
    { UNDEFINE, 40003, "XLATE_SRC_PORT" },
    { UNDEFINE, 40004, "XLATE_DST_PORT" },
    { UNDEFINE, 40005, "FW_EVENT" },
    /* v9 nTop extensions. */
    { UNDEFINE,  80 + NTOP_BASE, "FRAGMENTS" },
    { UNDEFINE,  82 + NTOP_BASE, "CLIENT_NW_DELAY_SEC" },
    { UNDEFINE,  83 + NTOP_BASE, "CLIENT_NW_DELAY_USEC" },
    { UNDEFINE,  84 + NTOP_BASE, "SERVER_NW_DELAY_SEC" },
    { UNDEFINE,  85 + NTOP_BASE, "SERVER_NW_DELAY_USEC" },
    { UNDEFINE,  86 + NTOP_BASE, "APPL_LATENCY_SEC" },
    { UNDEFINE,  87 + NTOP_BASE, "APPL_LATENCY_USEC" },
    { UNDEFINE,  98 + NTOP_BASE, "ICMP_FLAGS" },
    { UNDEFINE, 101 + NTOP_BASE, "SRC_IP_COUNTRY" },
    { UNDEFINE, 102 + NTOP_BASE, "SRC_IP_CITY" },
    { UNDEFINE, 103 + NTOP_BASE, "DST_IP_COUNTRY" },
    { UNDEFINE, 104 + NTOP_BASE, "DST_IP_CITY" },
    { UNDEFINE, 105 + NTOP_BASE, "FLOW_PROTO_PORT" },
    { UNDEFINE, 106 + NTOP_BASE, "TUNNEL_ID" },
    { UNDEFINE, 107 + NTOP_BASE, "LONGEST_FLOW_PKT" },
    { UNDEFINE, 108 + NTOP_BASE, "SHORTEST_FLOW_PKT" },
    { UNDEFINE, 109 + NTOP_BASE, "RETRANSMITTED_IN_PKTS" },
    { UNDEFINE, 110 + NTOP_BASE, "RETRANSMITTED_OUT_PKTS" },
    { UNDEFINE, 111 + NTOP_BASE, "OOORDER_IN_PKTS" },
    { UNDEFINE, 112 + NTOP_BASE, "OOORDER_OUT_PKTS" },
    { UNDEFINE, 113 + NTOP_BASE, "UNTUNNELED_PROTOCOL" },
    { UNDEFINE, 114 + NTOP_BASE, "UNTUNNELED_IPV4_SRC_ADDR" },
    { UNDEFINE, 115 + NTOP_BASE, "UNTUNNELED_L4_SRC_PORT" },
    { UNDEFINE, 116 + NTOP_BASE, "UNTUNNELED_IPV4_DST_ADDR" },
    { UNDEFINE, 117 + NTOP_BASE, "UNTUNNELED_L4_DST_PORT" },
    { UNDEFINE, 120 + NTOP_BASE, "DUMP_PATH" },
    { UNDEFINE, 130 + NTOP_BASE, "SIP_CALL_ID" },
    { UNDEFINE, 131 + NTOP_BASE, "SIP_CALLING_PARTY" },
    { UNDEFINE, 132 + NTOP_BASE, "SIP_CALLED_PARTY" },
    { UNDEFINE, 133 + NTOP_BASE, "SIP_RTP_CODECS" },
    { UNDEFINE, 134 + NTOP_BASE, "SIP_INVITE_TIME" },
    { UNDEFINE, 135 + NTOP_BASE, "SIP_TRYING_TIME" },
    { UNDEFINE, 136 + NTOP_BASE, "SIP_RINGING_TIME" },
    { UNDEFINE, 137 + NTOP_BASE, "SIP_OK_TIME" },
    { UNDEFINE, 138 + NTOP_BASE, "SIP_BYE_TIME" },
    { UNDEFINE, 139 + NTOP_BASE, "SIP_RTP_SRC_IP" },
    { UNDEFINE, 140 + NTOP_BASE, "SIP_RTP_SRC_PORT" },
    { UNDEFINE, 141 + NTOP_BASE, "SIP_RTP_DST_IP" },
    { UNDEFINE, 142 + NTOP_BASE, "SIP_RTP_DST_PORT" },
    { UNDEFINE, 150 + NTOP_BASE, "RTP_FIRST_SSRC" },
    { UNDEFINE, 151 + NTOP_BASE, "RTP_FIRST_TS" },
    { UNDEFINE, 152 + NTOP_BASE, "RTP_LAST_SSRC" },
    { UNDEFINE, 153 + NTOP_BASE, "RTP_LAST_TS" },
    { UNDEFINE, 154 + NTOP_BASE, "RTP_IN_JITTER" },
    { UNDEFINE, 155 + NTOP_BASE, "RTP_OUT_JITTER" },
    { UNDEFINE, 156 + NTOP_BASE, "RTP_IN_PKT_LOST" },
    { UNDEFINE, 157 + NTOP_BASE, "RTP_OUT_PKT_LOST" },
    { UNDEFINE, 158 + NTOP_BASE, "RTP_OUT_PAYLOAD_TYPE" },
    { UNDEFINE, 159 + NTOP_BASE, "RTP_IN_MAX_DELTA" },
    { UNDEFINE, 160 + NTOP_BASE, "RTP_OUT_MAX_DELTA" },
    { UNDEFINE, 165 + NTOP_BASE, "L7_PROTO" },
    { UNDEFINE, 180 + NTOP_BASE, "HTTP_URL" },
    { UNDEFINE, 181 + NTOP_BASE, "HTTP_RET_CODE" },
    { UNDEFINE, 182 + NTOP_BASE, "HTTP_REFERER" },
    { UNDEFINE, 183 + NTOP_BASE, "HTTP_UA" },
    { UNDEFINE, 184 + NTOP_BASE, "HTTP_MIME" },
    { UNDEFINE, 185 + NTOP_BASE, "SMTP_MAIL_FROM" },
    { UNDEFINE, 186 + NTOP_BASE, "SMTP_RCPT_TO" },
    { UNDEFINE, 195 + NTOP_BASE, "MYSQL_SERVER_VERSION" },
    { UNDEFINE, 196 + NTOP_BASE, "MYSQL_USERNAME" },
    { UNDEFINE, 197 + NTOP_BASE, "MYSQL_DB" },
    { UNDEFINE, 198 + NTOP_BASE, "MYSQL_QUERY" },
    { UNDEFINE, 199 + NTOP_BASE, "MYSQL_RESPONSE" },
    { UNDEFINE, 0, NULL }
};

static const value_string2 v9_scope_field_types[] = {
    { 1, "System" },
    { 2, "Interface" },
    { 3, "Line Card" },
    { 4, "NetFlow Cache" },
    { 5, "Template" },
    { 0, NULL }
};

static const value_string2 v9_sampler_mode[] = {
    { 0, "Deterministic" },
    { 1, "UNKNOWN" },  /* "Time-Based" ?? */
    { 2, "Random" },
    { 0, NULL }
};

static const value_string2 v9_direction[] = {
    { 0, "Ingress" },
    { 1, "Egress" },
    { 0, NULL }
};

#endif /* DEF_H */
